### ISSUE TITLE
Support `use-inline-specifiers-lockfile-format` config option introduced in pnpm v7.7.0

### ISSUE THREAD

**Issue by mcmxcdev** [ocavue/pnpm-deduplicate#3]
First of all, amazing tool ;)

I have used it a couple of days ago and it worked just fine.

In the mean time, we have opted-in to the new `use-inline-specifiers-lockfile-format` config option: 
https://github.com/pnpm/pnpm/releases/tag/v7.7.0

When I run `npx pnpm-deduplicate` now, it ends up breaking with:

```
/home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/dependency-path/lib/index.js:72
    if (reference.startsWith('link:')) {
                  ^

TypeError: reference.startsWith is not a function
    at Object.refToRelative (/home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/dependency-path/lib/index.js:72:19)
    at /home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:62:32
    at Array.forEach (<anonymous>)
    at /home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:61:14
    at Array.forEach (<anonymous>)
    at lockfileWalker (/home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:54:17)
    at file:///home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:81:112
    at Array.map (<anonymous>)
    at getAllDependencies (file:///home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:81:56)
    at async findDuplicatePackages (file:///home/<user>/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:103:20)
```

**Comment by mcmxcdev** [comment]
Okay sorry, it seems this issue was on my end.

I just ran `npx pnpm-deduplicate --version` and it outputs 0.2.2 for me. I was under the assumption that `npx` should always fetch the latest version but it only does so with `npx pnpm-deduplicate@latest` ...
 
I installed the lib with `pnpm install -g pnpm-deduplicate` and now it all works again ;)
